version: '3'
services:
  ui:
   build: ../../refarch-cloudnative-wfd-ui/docker
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-ui:spring
   depends_on:
    - menu
   ports:
    - "80:8181"
   environment:
    - wfd.menu.url=http://menu:8180/menu

  menu:
   build: ../../refarch-cloudnative-wfd-menu/docker
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-menu:spring
   depends_on:
    - appetizer
    - entree
    - dessert
   ports:
    - "8180:8180"
   environment:
    - wfd.menu.appetizers.url=http://appetizer:8081/appetizers
    - wfd.menu.entrees.url=http://entree:8082/entrees
    - wfd.menu.desserts.url=http://dessert:8083/desserts

  appetizer:
   build: ../../refarch-cloudnative-wfd-appetizer/docker
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-appetizer:spring
   ports:
    - "8081:8081"

  entree:
   build: ../../refarch-cloudnative-wfd-entree/docker
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-entree:spring
   ports:
    - "8082:8082"

  dessert:
   build: ../../refarch-cloudnative-wfd-dessert/docker
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-dessert:spring
   ports:
    - "8083:8083"
