version: '3'
services:
  ui:
   build: ../../refarch-cloudnative-wfd-ui
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-ui:microprofile
   depends_on:
    - menu
   ports:
    - "80:9080"

  menu:
   build: ../../refarch-cloudnative-wfd-menu
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-menu:microprofile
   depends_on:
    - appetizer
    - entree
    - dessert
   ports:
    - "9180:9080"
   env_file:
    - wfd.env

  appetizer:
   build: ../../refarch-cloudnative-wfd-appetizer
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-appetizer:microprofile
   ports:
    - "9280:9080"

  entree:
   build: ../../refarch-cloudnative-wfd-entree
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-entree:microprofile
   ports:
    - "9380:9080"

  dessert:
   build: ../../refarch-cloudnative-wfd-dessert
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-dessert:microprofile
   ports:
    - "9480:9080"
