version: '3'
services:
  ui:
   build: ../../refarch-cloudnative-wfd-ui
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-ui:spring-cloud
   depends_on:
    - menu
   ports:
    - "80:8181"
   environment:
    - eureka.client.enabled=false
    - ribbon.eureka.enabled=false
    - menu-service.ribbon.listOfServers=http://menu:8180

  menu:
   build: ../../refarch-cloudnative-wfd-menu
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-menu:spring-cloud
   depends_on:
    - appetizer
    - entree
    - dessert
   ports:
    - "8180:8180"
   environment:
    - eureka.client.enabled=false
    - spring.cloud.bus.enabled=false
    - ribbon.eureka.enabled=false
    - appetizer-service.ribbon.listOfServers=http://appetizer:8081
    - entree-service.ribbon.listOfServers=http://entree:8082
    - dessert-service.ribbon.listOfServers=http://dessert:8083

  appetizer:
   build: ../../refarch-cloudnative-wfd-appetizer
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-appetizer:spring-cloud
   ports:
    - "8081:8081"
   environment:
     - eureka.client.enabled=false

  entree:
   build: ../../refarch-cloudnative-wfd-entree
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-entree:spring-cloud
   ports:
    - "8082:8082"
   environment:
     - eureka.client.enabled=false

  dessert:
   build: ../../refarch-cloudnative-wfd-dessert
   image: ${WFD_DOCKER_REPO:-ibmcase}/wfd-dessert:spring-cloud
   ports:
    - "8083:8083"
   environment:
     - eureka.client.enabled=false
