spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://spring-stack-zipkin-server

eureka:
  client:
    serviceUrl:
       defaultZone: http://spring-stack-spring-eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
