spring:
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8082

wfd:
  entree:
    order: 2
    type: dinner
    menu:
      - Spaguetti Bolognese
      - Pepper Smoked Sirloin
      - Haddock
